[package]
name = "ultima"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ux = "0.1.5"
modular-bitfield-msb = "0.11.2"
organum = { path = "organum" }
nix = "0.26.1"